spring:
  application:
    name: tool-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rentflow_tool
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
